### PR TITLE
Retry button & userfriendly error message added

### LINKED ISSUE #111: Active criteria can be overlayed by bigger criteria
When a country has more deaths or recovered than active the active value will be overlayed!

### LINKED ISSUE #112: Unexpected Answer error happens often and is not user friendly
The Unexpected Answer Error happens often when creating a statistic. Please let the user know what that error means and maybe add a retry button to the error message.

### PR DESCRIPTION
**Pull request by Tommy-FF**

### CODE REVIEW

**Comment by Tommy-FF** [comment]
This Pull-Request now also fixes the error of bigger bars overlaying smaller ones when active is a criteria

**Comment by Tommy-FF** [comment]
Falsely closed

**Review by aleksn41 — APPROVED** [review]
you need to manually resolve the merge confilct, before i can merge this pull request

**Comment by Tommy-FF** [comment]
got it

**Comment by aleksn41** [comment]
it seems you merged the files wrongly, since the merged files do not build correctly. Resolve this so we can merge this pull request.

**Comment by Tommy-FF** [comment]
Already on it

**Pull request merged**
